### ISSUE TITLE
Invalid rank specifier: expected ',' or ']' when IReadOnlyList of IReadOnlyList is used

### ISSUE THREAD

**Issue by samyonr** [riok/mapperly#1377]
**Describe the bug**
When using IReadOnlyList<IReadOnlyList<X>>, the error below fails compiling:
```
0>ModelsMapper.g.cs(43,65): Error CS1586 : Array creation must have array size or array initializer
0>ModelsMapper.g.cs(43,68): Error CS0178 : Invalid rank specifier: expected ',' or ']'
```
Probably related to this line:
```csharp
var target = new global::MapperlyBug.DestTimeValueId[][source.Count];
```
Works fine in version 3.3.0. Fails in 3.4.0, 3.5.0, 3.5.1, 3.6.0.

**Declaration code**
See gist here: https://gist.github.com/samyonr/a80807a4d4849b6c04ed817155ea24f2

`Program.cs`
```csharp
using MapperlyBug;

var src = new SrcResultsSet(new []
{
    new []
    {
        new SrcTimeValueId()
    }
});

var mapper = new ModelsMapper();

var dest = mapper.Convert(src);

Console.WriteLine(dest);
```
`SrcResultsSet.cs`
```csharp
namespace MapperlyBug;

public record struct SrcTimeValueId(DateTime Time, double Value, int Id);

public record SrcResultsSet(IReadOnlyList<IReadOnlyList<SrcTimeValueId>> Results);
```
`DestResultsSet.cs`
```csharp
namespace MapperlyBug;

public partial record struct DestTimeValueId(DateTime Time, double Value, int? Id);

public partial class DestResultsSet
{
    public required IReadOnlyList<IReadOnlyList<DestTimeValueId>> Results { get; set; }

}
```
`ModelsMapper.cs`
```csharp
using Riok.Mapperly.Abstractions;

namespace MapperlyBug;

[Mapper]
public partial class ModelsMapper
{
    public partial DestResultsSet Convert(SrcResultsSet results);
}
```
`MapperlyBug.csproj`
```
<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Riok.Mapperly" Version="3.4.0" />
    </ItemGroup>

</Project>
```
`MapperlyBug.sln`
```

Microsoft Visual Studio Solution File, Format Version 12.00
Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "MapperlyBug", "MapperlyBug\MapperlyBug.csproj", "{57389106-DE16-4645-A336-03592C00B767}"
EndProject
Global
	GlobalSection(SolutionConfigurationPlatforms) = preSolution
		Debug|Any CPU = Debug|Any CPU
		Release|Any CPU = Release|Any CPU
	EndGlobalSection
	GlobalSection(ProjectConfigurationPlatforms) = postSolution
		{57389106-DE16-4645-A336-03592C00B767}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
		{57389106-DE16-4645-A336-03592C00B767}.Debug|Any CPU.Build.0 = Debug|Any CPU
		{57389106-DE16-4645-A336-03592C00B767}.Release|Any CPU.ActiveCfg = Release|Any CPU
		{57389106-DE16-4645-A336-03592C00B767}.Release|Any CPU.Build.0 = Release|Any CPU
	EndGlobalSection
EndGlobal
```

**Actual relevant generated code**
This is what's generated in version 3.4.0, `ModelsMapper.g.cs` and works:
```csharp
// <auto-generated />
#nullable enable
namespace MapperlyBug
{
    public partial class ModelsMapper
    {
        [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "3.4.0.0")]
        public partial global::MapperlyBug.DestResultsSet Convert(global::MapperlyBug.SrcResultsSet results)
        {
            var target = new global::MapperlyBug.DestResultsSet()
            {
                Results = MapToIReadOnlyListArray(results.Results),
            };
            return target;
        }

        [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "3.4.0.0")]
        private global::MapperlyBug.DestTimeValueId MapToDestTimeValueId(global::MapperlyBug.SrcTimeValueId source)
        {
            var target = new global::MapperlyBug.DestTimeValueId();
            target.Time = source.Time;
            target.Value = source.Value;
            target.Id = source.Id;
            return target;
        }

        [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "3.4.0.0")]
        private global::MapperlyBug.DestTimeValueId[] MapToDestTimeValueIdArray(global::System.Collections.Generic.IReadOnlyCollection<global::MapperlyBug.SrcTimeValueId> source)
        {
            var target = new global::MapperlyBug.DestTimeValueId[source.Count];
            var i = 0;
            foreach (var item in source)
            {
                target[i] = MapToDestTimeValueId(item);
                i++;
            }
            return target;
        }

        [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "3.4.0.0")]
        private global::System.Collections.Generic.IReadOnlyList<global::MapperlyBug.DestTimeValueId>[] MapToIReadOnlyListArray(global::System.Collections.Generic.IReadOnlyCollection<global::System.Collections.Generic.IReadOnlyList<global::MapperlyBug.SrcTimeValueId>> source)
        {
            var target = new global::MapperlyBug.DestTimeValueId[][source.Count];
            var i = 0;
            foreach (var item in source)
            {
                target[i] = MapToDestTimeValueIdArray(item);
                i++;
            }
            return target;
        }
    }
}
```

**Expected relevant generated code**
This is what's generated in version 3.3.0, `ModelsMapper.g.cs` and works:
```csharp
// <auto-generated />
#nullable enable
namespace MapperlyBug
{
    public partial class ModelsMapper
    {
        public partial global::MapperlyBug.DestResultsSet Convert(global::MapperlyBug.SrcResultsSet results)
        {
            var target = new global::MapperlyBug.DestResultsSet()
            {
                Results = MapToIReadOnlyList1(results.Results),
            };
            return target;
        }

        private global::MapperlyBug.DestTimeValueId MapToDestTimeValueId(global::MapperlyBug.SrcTimeValueId source)
        {
            var target = new global::MapperlyBug.DestTimeValueId();
            target.Time = source.Time;
            target.Value = source.Value;
            target.Id = source.Id;
            return target;
        }

        private global::System.Collections.Generic.IReadOnlyList<global::MapperlyBug.DestTimeValueId> MapToIReadOnlyList(global::System.Collections.Generic.IReadOnlyList<global::MapperlyBug.SrcTimeValueId> source)
        {
            var target = new global::MapperlyBug.DestTimeValueId[source.Count];
            var i = 0;
            foreach (var item in source)
            {
                target[i] = MapToDestTimeValueId(item);
                i++;
            }
            return target;
        }

        private global::System.Collections.Generic.IReadOnlyList<global::System.Collections.Generic.IReadOnlyList<global::MapperlyBug.DestTimeValueId>> MapToIReadOnlyList1(global::System.Collections.Generic.IReadOnlyList<global::System.Collections.Generic.IReadOnlyList<global::MapperlyBug.SrcTimeValueId>> source)
        {
            var target = new global::System.Collections.Generic.IReadOnlyList<global::MapperlyBug.DestTimeValueId>[source.Count];
            var i = 0;
            foreach (var item in source)
            {
                target[i] = MapToIReadOnlyList(item);
                i++;
            }
            return target;
        }
    }
}
```

**Environment:**
- Mapperly Version: 3.4.0, 3.5.0, 3.5.1, 3.6.0
- Nullable reference types: enabled.
- .NET Version: .NET 8
- Target Framework: .net.8.0
- Compiler Version: '4.9.2-3.24171.17 (a7431003)'
- C# Language Version: 12.0
- IDE: Rider 2024.1.2
- OS: Windows 11
