### ISSUE TITLE
Syntax node is not within syntax tree

### ISSUE THREAD

**Issue by jjr2000** [riok/mapperly#1766]
**Please do the checklist before filing an issue:**
- [X] I have read the [documentation](https://mapperly.riok.app), including the [FAQ](https://mapperly.riok.app/docs/getting-started/faq/)

- [X] I can reproduce the bug using the latest prerelease version
- [X] I have searched existing [discussion](https://github.com/riok/mapperly/discussions) and [issue](https://github.com/riok/mapperly/issues) to avoid duplicates

**Describe the bug**
After Upgrading from 4.1.1 to 4.2.0 Mapperly is no longer able to generate code. Downgrading back to 4.1.1 fixes the issue.

**Stack Trace**
```csharp
Generator 'MapperGenerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'ArgumentException' with message 'Syntax node is not within syntax tree'.
System.ArgumentException: Syntax node is not within syntax tree
at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetSymbolInfo(ExpressionSyntax expression, CancellationToken cancellationToken) in Z:\BuildAgent\work\3b7ce003563d6f8f\src\Compilers\CSharp\Portable\Compilation\CSharpSemanticModel.cs:line 521
at Riok.Mapperly.Descriptors.InlineExpressionRewriter.VisitMemberAccessExpression(MemberAccessExpressionSyntax node) in /_/src/Riok.Mapperly/Descriptors/InlineExpressionRewriter.cs:line 60
at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.Visit(SyntaxNode node) in Z:\BuildAgent\work\3b7ce003563d6f8f\src\Compilers\CSharp\Portable\Syntax\CSharpSyntaxRewriter.cs:line 41
at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitArgument(ArgumentSyntax node) in Z:\BuildAgent\work\3b7ce003563d6f8f\src\Compilers\CSharp\Portable\Generated\CSharpSyntaxGenerator\CSharpSyntaxGenerator.SourceGenerator\Syntax.xml.Main.Generated.cs:line 1636
at Microsoft.CodeAnalysis.CSharp.Syntax.ArgumentSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor) in Z:\BuildAgent\work\3b7ce003563d6f8f\src\Compilers\CSharp\Portable\Generated\CSharpSyntaxGenerator\CSharpSyntaxGenerator.SourceGenerator\Syntax.xml.Syntax.Generated.cs:line 2775
at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.Visit(SyntaxNode node) in Z:\BuildAgent\work\3b7ce003563d6f8f\src\Compilers\CSharp\Portable\Syntax\CSharpSyntaxRewriter.cs:line 41
at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitListElement[TNode](TNode node) in Z:\BuildAgent\work\3b7ce003563d6f8f\src\Compilers\CSharp\Portable\Syntax\CSharpSyntaxRewriter.cs:line 168
at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitList[TNode](SeparatedSyntaxList`1 list) in Z:\BuildAgent\work\3b7ce003563d6f8f\src\Compilers\CSharp\Portable\Syntax\CSharpSyntaxRewriter.cs:line 173
at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitArgumentList(ArgumentListSyntax node) in Z:\BuildAgent\work\3b7ce003563d6f8f\src\Compilers\CSharp\Portable\Generated\CSharpSyntaxGenerator\CSharpSyntaxGenerator.SourceGenerator\Syntax.xml.Main.Generated.cs:line 1630
at Microsoft.CodeAnalysis.CSharp.Syntax.ArgumentListSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor) in Z:\BuildAgent\work\3b7ce003563d6f8f\src\Compilers\CSharp\Portable\Generated\CSharpSyntaxGenerator\CSharpSyntaxGenerator.SourceGenerator\Syntax.xml.Syntax.Generated.cs:line 2642
at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.Visit(SyntaxNode node) in Z:\BuildAgent\work\3b7ce003563d6f8f\src\Compilers\CSharp\Portable\Syntax\CSharpSyntaxRewriter.cs:line 41
at Riok.Mapperly.Descriptors.InlineExpressionRewriter.VisitStaticMethodInvocation(InvocationExpressionSyntax node, IMethodSymbol methodSymbol) in /_/src/Riok.Mapperly/Descriptors/InlineExpressionRewriter.cs:line 237
at Riok.Mapperly.Descriptors.InlineExpressionRewriter.VisitInvocationExpression(InvocationExpressionSyntax node) in /_/src/Riok.Mapperly/Descriptors/InlineExpressionRewriter.cs:line 166
at Microsoft.CodeAnalysis.CSharp.Syntax.InvocationExpressionSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor) in Z:\BuildAgent\work\3b7ce003563d6f8f\src\Compilers\CSharp\Portable\Generated\CSharpSyntaxGenerator\CSharpSyntaxGenerator.SourceGenerator\Syntax.xml.Syntax.Generated.cs:line 2508
at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.Visit(SyntaxNode node) in Z:\BuildAgent\work\3b7ce003563d6f8f\src\Compilers\CSharp\Portable\Syntax\CSharpSyntaxRewriter.cs:line 41
at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitConditionalExpression(ConditionalExpressionSyntax node) in Z:\BuildAgent\work\3b7ce003563d6f8f\src\Compilers\CSharp\Portable\Generated\CSharpSyntaxGenerator\CSharpSyntaxGenerator.SourceGenerator\Syntax.xml.Main.Generated.cs:line 1588
at Microsoft.CodeAnalysis.CSharp.Syntax.ConditionalExpressionSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor) in Z:\BuildAgent\work\3b7ce003563d6f8f\src\Compilers\CSharp\Portable\Generated\CSharpSyntaxGenerator\CSharpSyntaxGenerator.SourceGenerator\Syntax.xml.Syntax.Generated.cs:line 1877
at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.Visit(SyntaxNode node) in Z:\BuildAgent\work\3b7ce003563d6f8f\src\Compilers\CSharp\Portable\Syntax\CSharpSyntaxRewriter.cs:line 41
at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitAssignmentExpression(AssignmentExpressionSyntax node) in Z:\BuildAgent\work\3b7ce003563d6f8f\src\Compilers\CSharp\Portable\Generated\CSharpSyntaxGenerator\CSharpSyntaxGenerator.SourceGenerator\Syntax.xml.Main.Generated.cs:line 1585
at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.Visit(SyntaxNode node) in Z:\BuildAgent\work\3b7ce003563d6f8f\src\Compilers\CSharp\Portable\Syntax\CSharpSyntaxRewriter.cs:line 41
at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitListElement[TNode](TNode node) in Z:\BuildAgent\work\3b7ce003563d6f8f\src\Compilers\CSharp\Portable\Syntax\CSharpSyntaxRewriter.cs:line 168
at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitList[TNode](SeparatedSyntaxList`1 list) in Z:\BuildAgent\work\3b7ce003563d6f8f\src\Compilers\CSharp\Portable\Syntax\CSharpSyntaxRewriter.cs:line 173
at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitInitializerExpression(InitializerExpressionSyntax node) in Z:\BuildAgent\work\3b7ce003563d6f8f\src\Compilers\CSharp\Portable\Generated\CSharpSyntaxGenerator\CSharpSyntaxGenerator.SourceGenerator\Syntax.xml.Main.Generated.cs:line 1663
at Riok.Mapperly.Descriptors.InlineExpressionRewriter.VisitImplicitObjectCreationExpression(ImplicitObjectCreationExpressionSyntax node) in /_/src/Riok.Mapperly/Descriptors/InlineExpressionRewriter.cs:line 116
at Microsoft.CodeAnalysis.CSharp.Syntax.ImplicitObjectCreationExpressionSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor) in Z:\BuildAgent\work\3b7ce003563d6f8f\src\Compilers\CSharp\Portable\Generated\CSharpSyntaxGenerator\CSharpSyntaxGenerator.SourceGenerator\Syntax.xml.Syntax.Generated.cs:line 3600
at Riok.Mapperly.Descriptors.MappingBuilders.InlineExpressionMappingBuilder.TryBuildMapping(InlineExpressionMappingBuilderContext ctx, UserImplementedMethodMapping mapping) in /_/src/Riok.Mapperly/Descriptors/MappingBuilders/InlineExpressionMappingBuilder.cs:line 49
at Riok.Mapperly.Descriptors.InlineExpressionMappingBuilderContext.TryInlineMapping(INewInstanceMapping mapping) in /_/src/Riok.Mapperly/Descriptors/InlineExpressionMappingBuilderContext.cs:line 206
at Riok.Mapperly.Descriptors.InlineExpressionMappingBuilderContext.FindNamedMapping(String mappingName) in /_/src/Riok.Mapperly/Descriptors/InlineExpressionMappingBuilderContext.cs:line 65
at Riok.Mapperly.Descriptors.MappingBuilders.UseNamedMappingBuilder.TryBuildMapping(MappingBuilderContext ctx) in /_/src/Riok.Mapperly/Descriptors/MappingBuilders/UseNamedMappingBuilder.cs:line 15
at Riok.Mapperly.Descriptors.MappingBuilders.MappingBuilder.Build(MappingBuilderContext ctx, Boolean resultIsReusable) in /_/src/Riok.Mapperly/Descriptors/MappingBuilders/MappingBuilder.cs:line 64
at Riok.Mapperly.Descriptors.InlineExpressionMappingBuilderContext.BuildMapping(IUserMapping userMapping, TypeMappingKey mappingKey, MappingBuildingOptions options, Location diagnosticLocation) in /_/src/Riok.Mapperly/Descriptors/InlineExpressionMappingBuilderContext.cs:line 148
at Riok.Mapperly.Descriptors.InlineExpressionMappingBuilderContext.BuildMapping(TypeMappingKey mappingKey, MappingBuildingOptions options, Location diagnosticLocation) in /_/src/Riok.Mapperly/Descriptors/InlineExpressionMappingBuilderContext.cs:line 132
at Riok.Mapperly.Descriptors.MappingBodyBuilders.MemberMappingBuilder.TryBuild(IMembersBuilderContext`1 ctx, MemberMappingInfo memberMappingInfo, CodeStyle codeStyle, ISourceValue& sourceValue) in /_/src/Riok.Mapperly/Descriptors/MappingBodyBuilders/MemberMappingBuilder.cs:line 68
at Riok.Mapperly.Descriptors.MappingBodyBuilders.MemberMappingBuilder.TryBuildAssignment(IMembersBuilderContext`1 ctx, MemberMappingInfo memberInfo, MemberAssignmentMapping& mapping) in /_/src/Riok.Mapperly/Descriptors/MappingBodyBuilders/MemberMappingBuilder.cs:line 50
at Riok.Mapperly.Descriptors.MappingBodyBuilders.NewInstanceObjectMemberMappingBodyBuilder.BuildInitMemberMapping(INewInstanceBuilderContext`1 ctx, MemberMappingInfo memberInfo) in /_/src/Riok.Mapperly/Descriptors/MappingBodyBuilders/NewInstanceObjectMemberMappingBodyBuilder.cs:line 149
at Riok.Mapperly.Descriptors.MappingBodyBuilders.NewInstanceObjectMemberMappingBodyBuilder.BuildInitMemberMappings(INewInstanceBuilderContext`1 ctx, Boolean includeAllMembers) in /_/src/Riok.Mapperly/Descriptors/MappingBodyBuilders/NewInstanceObjectMemberMappingBodyBuilder.cs:line 113
at Riok.Mapperly.Descriptors.MappingBodyBuilders.NewInstanceObjectMemberMappingBodyBuilder.BuildMappingBody(MappingBuilderContext ctx, NewInstanceObjectMemberMapping mapping) in /_/src/Riok.Mapperly/Descriptors/MappingBodyBuilders/NewInstanceObjectMemberMappingBodyBuilder.cs:line 22
at Riok.Mapperly.Descriptors.MappingBodyBuilders.MappingBodyBuilder.BuildMappingBodies(CancellationToken cancellationToken) in /_/src/Riok.Mapperly/Descriptors/MappingBodyBuilders/MappingBodyBuilder.cs:line 30
at Riok.Mapperly.Descriptors.DescriptorBuilder.Build(CancellationToken cancellationToken) in /_/src/Riok.Mapperly/Descriptors/DescriptorBuilder.cs:line 88
at Riok.Mapperly.MapperGenerator.BuildDescriptor(CompilationContext compilationContext, MapperDeclaration mapperDeclaration, MapperConfiguration mapperDefaults, CancellationToken cancellationToken) in /_/src/Riok.Mapperly/MapperGenerator.cs:line 97
at Riok.Mapperly.MapperGenerator.c. b__2_3(ValueTuple`2 x, CancellationToken ct) in /_/src/Riok.Mapperly/MapperGenerator.cs:line 65
at Microsoft.CodeAnalysis.TransformNode`2.c__DisplayClass6_0..ctor>b__0(TInput i, CancellationToken token) in Z:\BuildAgent\work\3b7ce003563d6f8f\src\Compilers\Core\Portable\SourceGeneration\Nodes\TransformNode.cs:line 27
at Microsoft.CodeAnalysis.TransformNode`2.UpdateStateTable(Builder builder, NodeStateTable`1 previousTable, CancellationToken cancellationToken) in Z:\BuildAgent\work\3b7ce003563d6f8f\src\Compilers\Core\Portable\SourceGeneration\Nodes\TransformNode.cs:line 83
-----


System.ArgumentException: Syntax node is not within syntax tree
at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetSymbolInfo(ExpressionSyntax expression, CancellationToken cancellationToken) in Z:\BuildAgent\work\3b7ce003563d6f8f\src\Compilers\CSharp\Portable\Compilation\CSharpSemanticModel.cs:line 521
at Riok.Mapperly.Descriptors.InlineExpressionRewriter.VisitMemberAccessExpression(MemberAccessExpressionSyntax node) in /_/src/Riok.Mapperly/Descriptors/InlineExpressionRewriter.cs:line 60
at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.Visit(SyntaxNode node) in Z:\BuildAgent\work\3b7ce003563d6f8f\src\Compilers\CSharp\Portable\Syntax\CSharpSyntaxRewriter.cs:line 41
at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitArgument(ArgumentSyntax node) in Z:\BuildAgent\work\3b7ce003563d6f8f\src\Compilers\CSharp\Portable\Generated\CSharpSyntaxGenerator\CSharpSyntaxGenerator.SourceGenerator\Syntax.xml.Main.Generated.cs:line 1636
at Microsoft.CodeAnalysis.CSharp.Syntax.ArgumentSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor) in Z:\BuildAgent\work\3b7ce003563d6f8f\src\Compilers\CSharp\Portable\Generated\CSharpSyntaxGenerator\CSharpSyntaxGenerator.SourceGenerator\Syntax.xml.Syntax.Generated.cs:line 2775
at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.Visit(SyntaxNode node) in Z:\BuildAgent\work\3b7ce003563d6f8f\src\Compilers\CSharp\Portable\Syntax\CSharpSyntaxRewriter.cs:line 41
at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitListElement[TNode](TNode node) in Z:\BuildAgent\work\3b7ce003563d6f8f\src\Compilers\CSharp\Portable\Syntax\CSharpSyntaxRewriter.cs:line 168
at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitList[TNode](SeparatedSyntaxList`1 list) in Z:\BuildAgent\work\3b7ce003563d6f8f\src\Compilers\CSharp\Portable\Syntax\CSharpSyntaxRewriter.cs:line 173
at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitArgumentList(ArgumentListSyntax node) in Z:\BuildAgent\work\3b7ce003563d6f8f\src\Compilers\CSharp\Portable\Generated\CSharpSyntaxGenerator\CSharpSyntaxGenerator.SourceGenerator\Syntax.xml.Main.Generated.cs:line 1630
at Microsoft.CodeAnalysis.CSharp.Syntax.ArgumentListSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor) in Z:\BuildAgent\work\3b7ce003563d6f8f\src\Compilers\CSharp\Portable\Generated\CSharpSyntaxGenerator\CSharpSyntaxGenerator.SourceGenerator\Syntax.xml.Syntax.Generated.cs:line 2642
at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.Visit(SyntaxNode node) in Z:\BuildAgent\work\3b7ce003563d6f8f\src\Compilers\CSharp\Portable\Syntax\CSharpSyntaxRewriter.cs:line 41
at Riok.Mapperly.Descriptors.InlineExpressionRewriter.VisitStaticMethodInvocation(InvocationExpressionSyntax node, IMethodSymbol methodSymbol) in /_/src/Riok.Mapperly/Descriptors/InlineExpressionRewriter.cs:line 237
at Riok.Mapperly.Descriptors.InlineExpressionRewriter.VisitInvocationExpression(InvocationExpressionSyntax node) in /_/src/Riok.Mapperly/Descriptors/InlineExpressionRewriter.cs:line 166
at Microsoft.CodeAnalysis.CSharp.Syntax.InvocationExpressionSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor) in Z:\BuildAgent\work\3b7ce003563d6f8f\src\Compilers\CSharp\Portable\Generated\CSharpSyntaxGenerator\CSharpSyntaxGenerator.SourceGenerator\Syntax.xml.Syntax.Generated.cs:line 2508
at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.Visit(SyntaxNode node) in Z:\BuildAgent\work\3b7ce003563d6f8f\src\Compilers\CSharp\Portable\Syntax\CSharpSyntaxRewriter.cs:line 41
at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitConditionalExpression(ConditionalExpressionSyntax node) in Z:\BuildAgent\work\3b7ce003563d6f8f\src\Compilers\CSharp\Portable\Generated\CSharpSyntaxGenerator\CSharpSyntaxGenerator.SourceGenerator\Syntax.xml.Main.Generated.cs:line 1588
at Microsoft.CodeAnalysis.CSharp.Syntax.ConditionalExpressionSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor) in Z:\BuildAgent\work\3b7ce003563d6f8f\src\Compilers\CSharp\Portable\Generated\CSharpSyntaxGenerator\CSharpSyntaxGenerator.SourceGenerator\Syntax.xml.Syntax.Generated.cs:line 1877
at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.Visit(SyntaxNode node) in Z:\BuildAgent\work\3b7ce003563d6f8f\src\Compilers\CSharp\Portable\Syntax\CSharpSyntaxRewriter.cs:line 41
at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitAssignmentExpression(AssignmentExpressionSyntax node) in Z:\BuildAgent\work\3b7ce003563d6f8f\src\Compilers\CSharp\Portable\Generated\CSharpSyntaxGenerator\CSharpSyntaxGenerator.SourceGenerator\Syntax.xml.Main.Generated.cs:line 1585
at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.Visit(SyntaxNode node) in Z:\BuildAgent\work\3b7ce003563d6f8f\src\Compilers\CSharp\Portable\Syntax\CSharpSyntaxRewriter.cs:line 41
at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitListElement[TNode](TNode node) in Z:\BuildAgent\work\3b7ce003563d6f8f\src\Compilers\CSharp\Portable\Syntax\CSharpSyntaxRewriter.cs:line 168
at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitList[TNode](SeparatedSyntaxList`1 list) in Z:\BuildAgent\work\3b7ce003563d6f8f\src\Compilers\CSharp\Portable\Syntax\CSharpSyntaxRewriter.cs:line 173
at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitInitializerExpression(InitializerExpressionSyntax node) in Z:\BuildAgent\work\3b7ce003563d6f8f\src\Compilers\CSharp\Portable\Generated\CSharpSyntaxGenerator\CSharpSyntaxGenerator.SourceGenerator\Syntax.xml.Main.Generated.cs:line 1663
at Riok.Mapperly.Descriptors.InlineExpressionRewriter.VisitImplicitObjectCreationExpression(ImplicitObjectCreationExpressionSyntax node) in /_/src/Riok.Mapperly/Descriptors/InlineExpressionRewriter.cs:line 116
at Microsoft.CodeAnalysis.CSharp.Syntax.ImplicitObjectCreationExpressionSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor) in Z:\BuildAgent\work\3b7ce003563d6f8f\src\Compilers\CSharp\Portable\Generated\CSharpSyntaxGenerator\CSharpSyntaxGenerator.SourceGenerator\Syntax.xml.Syntax.Generated.cs:line 3600
at Riok.Mapperly.Descriptors.MappingBuilders.InlineExpressionMappingBuilder.TryBuildMapping(InlineExpressionMappingBuilderContext ctx, UserImplementedMethodMapping mapping) in /_/src/Riok.Mapperly/Descriptors/MappingBuilders/InlineExpressionMappingBuilder.cs:line 49
at Riok.Mapperly.Descriptors.InlineExpressionMappingBuilderContext.TryInlineMapping(INewInstanceMapping mapping) in /_/src/Riok.Mapperly/Descriptors/InlineExpressionMappingBuilderContext.cs:line 206
at Riok.Mapperly.Descriptors.InlineExpressionMappingBuilderContext.FindNamedMapping(String mappingName) in /_/src/Riok.Mapperly/Descriptors/InlineExpressionMappingBuilderContext.cs:line 65
at Riok.Mapperly.Descriptors.MappingBuilders.UseNamedMappingBuilder.TryBuildMapping(MappingBuilderContext ctx) in /_/src/Riok.Mapperly/Descriptors/MappingBuilders/UseNamedMappingBuilder.cs:line 15
at Riok.Mapperly.Descriptors.MappingBuilders.MappingBuilder.Build(MappingBuilderContext ctx, Boolean resultIsReusable) in /_/src/Riok.Mapperly/Descriptors/MappingBuilders/MappingBuilder.cs:line 64
at Riok.Mapperly.Descriptors.InlineExpressionMappingBuilderContext.BuildMapping(IUserMapping userMapping, TypeMappingKey mappingKey, MappingBuildingOptions options, Location diagnosticLocation) in /_/src/Riok.Mapperly/Descriptors/InlineExpressionMappingBuilderContext.cs:line 148
at Riok.Mapperly.Descriptors.InlineExpressionMappingBuilderContext.BuildMapping(TypeMappingKey mappingKey, MappingBuildingOptions options, Location diagnosticLocation) in /_/src/Riok.Mapperly/Descriptors/InlineExpressionMappingBuilderContext.cs:line 132
at Riok.Mapperly.Descriptors.MappingBodyBuilders.MemberMappingBuilder.TryBuild(IMembersBuilderContext`1 ctx, MemberMappingInfo memberMappingInfo, CodeStyle codeStyle, ISourceValue& sourceValue) in /_/src/Riok.Mapperly/Descriptors/MappingBodyBuilders/MemberMappingBuilder.cs:line 68
at Riok.Mapperly.Descriptors.MappingBodyBuilders.MemberMappingBuilder.TryBuildAssignment(IMembersBuilderContext`1 ctx, MemberMappingInfo memberInfo, MemberAssignmentMapping& mapping) in /_/src/Riok.Mapperly/Descriptors/MappingBodyBuilders/MemberMappingBuilder.cs:line 50
at Riok.Mapperly.Descriptors.MappingBodyBuilders.NewInstanceObjectMemberMappingBodyBuilder.BuildInitMemberMapping(INewInstanceBuilderContext`1 ctx, MemberMappingInfo memberInfo) in /_/src/Riok.Mapperly/Descriptors/MappingBodyBuilders/NewInstanceObjectMemberMappingBodyBuilder.cs:line 149
at Riok.Mapperly.Descriptors.MappingBodyBuilders.NewInstanceObjectMemberMappingBodyBuilder.BuildInitMemberMappings(INewInstanceBuilderContext`1 ctx, Boolean includeAllMembers) in /_/src/Riok.Mapperly/Descriptors/MappingBodyBuilders/NewInstanceObjectMemberMappingBodyBuilder.cs:line 113
at Riok.Mapperly.Descriptors.MappingBodyBuilders.NewInstanceObjectMemberMappingBodyBuilder.BuildMappingBody(MappingBuilderContext ctx, NewInstanceObjectMemberMapping mapping) in /_/src/Riok.Mapperly/Descriptors/MappingBodyBuilders/NewInstanceObjectMemberMappingBodyBuilder.cs:line 22
at Riok.Mapperly.Descriptors.MappingBodyBuilders.MappingBodyBuilder.BuildMappingBodies(CancellationToken cancellationToken) in /_/src/Riok.Mapperly/Descriptors/MappingBodyBuilders/MappingBodyBuilder.cs:line 30
at Riok.Mapperly.Descriptors.DescriptorBuilder.Build(CancellationToken cancellationToken) in /_/src/Riok.Mapperly/Descriptors/DescriptorBuilder.cs:line 88
at Riok.Mapperly.MapperGenerator.BuildDescriptor(CompilationContext compilationContext, MapperDeclaration mapperDeclaration, MapperConfiguration mapperDefaults, CancellationToken cancellationToken) in /_/src/Riok.Mapperly/MapperGenerator.cs:line 97
at Riok.Mapperly.MapperGenerator.c. b__2_3(ValueTuple`2 x, CancellationToken ct) in /_/src/Riok.Mapperly/MapperGenerator.cs:line 65
at Microsoft.CodeAnalysis.TransformNode`2.c__DisplayClass6_0..ctor>b__0(TInput i, CancellationToken token) in Z:\BuildAgent\work\3b7ce003563d6f8f\src\Compilers\Core\Portable\SourceGeneration\Nodes\TransformNode.cs:line 27
at Microsoft.CodeAnalysis.TransformNode`2.UpdateStateTable(Builder builder, NodeStateTable`1 previousTable, CancellationToken cancellationToken) in Z:\BuildAgent\work\3b7ce003563d6f8f\src\Compilers\Core\Portable\SourceGeneration\Nodes\TransformNode.cs:line 83
```

**Environment (please complete the following information):**
- Mapperly Version: 4.2.0
- Nullable reference types: enabled
- .NET Version: .net 9.0.200
- Target Framework: .net9.0
- Compiler Version: 4.13.0-3.25072.11 (40a6eabe)
- C# Language Version: 13.0
- IDE: JetBrains Rider 2024.3.6
- OS: Windows 11 Pro 24H2

**Additional context**
I've noticed that the build error mentions a 'Z' drive, though it may not be relevant I feel it is worth noting that my machine has no such drive mapped.

**Comment by latonz** [comment]
Could you provide a minimal repro? Thanks!

**Comment by clegoz** [comment]
I had the same issue. I think it's because of the `WithAdditionalAnnotations` call
https://github.com/riok/mapperly/blob/547fd004c9711a5ffc17eb761835601b0f4b340c/src/Riok.Mapperly/Descriptors/InlineExpressionRewriter.cs#L156-L161

This is also happening with instance methods in v3.5.1.

Here's [repro](https://github.com/clegoz/mapperly-repro).

**Comment by latonz** [comment]
Thanks for the feedback. I'll look into it as soon as I have some time. If you'd like to contribute, feel free to do so. 😊 You can simply copy your repro code into a unit test and call `await TestHelper.VerifyGenerator(<your repro code>)` and start debugging.
