### ISSUE TITLE
MapperDefaults' EnumMappingStrategy is not applied to mappers

### ISSUE THREAD

**Issue by alhimik45** [riok/mapperly#946]
**Describe the bug**
Setting `EnumMappingStrategy.ByName` in `MapperDefaults` does not affect mappers.

**To Reproduce**
1. Add `MapperDefaults` attribute with `EnumMappingStrategy = EnumMappingStrategy.ByName`
2. Create two enums with same value names but different values.
3. Create mapper between them
4. Get diagnostic warnings RMG037 and RMG038 about not matched values
5. In generated code `ByValue` strategy is used instead of `ByName`

**Expected behavior**
Strategy `ByName` from `MapperDefaults` attrbbute is used

**Code snippets**
.editorconfig:
```
[*.cs]
dotnet_diagnostic.RMG037.severity = error # Unmapped target enum value
dotnet_diagnostic.RMG038.severity = error # Unmapped source enum value
```

Test code:
```
using Riok.Mapperly.Abstractions;

//this should affect mapper below
[assembly: MapperDefaults(EnumMappingStrategy = EnumMappingStrategy.ByName)]

var v = Enum1.Value2;
Console.WriteLine(v.Convert());

public enum Enum1
{
    Value1 = 4,
    Value2 = 7,
}

public enum Enum2
{
    Value1,
    Value2,
}

// [Mapper(EnumMappingStrategy = EnumMappingStrategy.ByName)]
[Mapper]
public static partial class Mapper
{
    public static partial Enum2 Convert(this Enum1 e);
}
```

**Environment (please complete the following information):**
- Mapperly Version: 3.2.0, 3.3.0-next4
- .NET Version: 6.0.124
- Target Framework: .net6.0
- IDE: Rider 2023.1.3
- OS: Arch Linux

**Comment by ni507** [comment]
It works for me. I can't reproduce the behaviour you describe.
Did the diagnostics occur?

```
Error RMG038 : Enum member Value1 (4) on Enum1 not found on target enum Enum2
Error RMG038 : Enum member Value2 (7) on Enum1 not found on target enum Enum2
Error RMG037 : Enum member Value1 (0) on Enum2 not found on source enum Enum1
Error RMG037 : Enum member Value2 (1) on Enum2 not found on source enum Enum1
```

And how does your generated code looks like?

**Comment by alhimik45** [comment]
[Link](https://github.com/alhimik45/mapperly-bug-reproduce) to full solution for reproduction.

<details><summary>dotnet build log</summary>
<p>

$ dotnet build
Microsoft (R) Build Engine version 17.0.1+b177f8fa7 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  Restored /tmp/hhh/mapperly-bug-reproduce/ConsoleApp1/ConsoleApp1.csproj (in 442 ms).
/tmp/hhh/mapperly-bug-reproduce/ConsoleApp1/Program.cs(24,5): error RMG038: Enum member Value1 (4) on Enum1 not found on target enum Enum2 [/tmp/hhh/mapperly-bug-reproduce/ConsoleApp1/ConsoleApp1.csproj]
/tmp/hhh/mapperly-bug-reproduce/ConsoleApp1/Program.cs(24,5): error RMG038: Enum member Value2 (7) on Enum1 not found on target enum Enum2 [/tmp/hhh/mapperly-bug-reproduce/ConsoleApp1/ConsoleApp1.csproj]
/tmp/hhh/mapperly-bug-reproduce/ConsoleApp1/Program.cs(24,5): error RMG037: Enum member Value1 (0) on Enum2 not found on source enum Enum1 [/tmp/hhh/mapperly-bug-reproduce/ConsoleApp1/ConsoleApp1.csproj]
/tmp/hhh/mapperly-bug-reproduce/ConsoleApp1/Program.cs(24,5): error RMG037: Enum member Value2 (1) on Enum2 not found on source enum Enum1 [/tmp/hhh/mapperly-bug-reproduce/ConsoleApp1/ConsoleApp1.csproj]

Build FAILED.

/tmp/hhh/mapperly-bug-reproduce/ConsoleApp1/Program.cs(24,5): error RMG038: Enum member Value1 (4) on Enum1 not found on target enum Enum2 [/tmp/hhh/mapperly-bug-reproduce/ConsoleApp1/ConsoleApp1.csproj]
/tmp/hhh/mapperly-bug-reproduce/ConsoleApp1/Program.cs(24,5): error RMG038: Enum member Value2 (7) on Enum1 not found on target enum Enum2 [/tmp/hhh/mapperly-bug-reproduce/ConsoleApp1/ConsoleApp1.csproj]
/tmp/hhh/mapperly-bug-reproduce/ConsoleApp1/Program.cs(24,5): error RMG037: Enum member Value1 (0) on Enum2 not found on source enum Enum1 [/tmp/hhh/mapperly-bug-reproduce/ConsoleApp1/ConsoleApp1.csproj]
/tmp/hhh/mapperly-bug-reproduce/ConsoleApp1/Program.cs(24,5): error RMG037: Enum member Value2 (1) on Enum2 not found on source enum Enum1 [/tmp/hhh/mapperly-bug-reproduce/ConsoleApp1/ConsoleApp1.csproj]
    0 Warning(s)
    4 Error(s)

Time Elapsed 00:00:01.81

</p>
</details> 

And yeah, when `ByName` only in `MapperDefaults` generated code also looks like ByValue strategy is used

```
public static partial class Mapper
{
    public static partial global::Enum2 Convert(this global::Enum1 e)
    {
        return (global::Enum2)e;
    }
}
```

**Comment by ni507** [comment]
I was able to reproduce it with dotnet 6.0.x. I will look into it.

Maybe as a workaround -> It works with dotnet 7.0.x.

**Comment by latonz** [comment]
@alhimik45 This should be fixed in `3.3.0-next.6`, could you check?

**Comment by alhimik45** [comment]
Yes, seems to be working fine
